data:
  input_folder: "/home/mircore/Desktop/Phd/Aman/DATA/imerg_data"
  file_pattern: "imerg_daily_2016*.nc4"
  variable_name: "MWprecipitation"
  data_type: "nc4"

date_range:
  start: "2016-03-23"
  end: "2016-03-27"  

visualization:
  region:
    lon_min: 40
    lon_max: 120
    lat_min: -35
    lat_max: 40
  colormap: "RdYlBu_r"
  normalization:
    type: "log"
    vmin: 0.1
    vmax: 100
  figure:
    size: [12, 10]
    dpi: 150
  map_features:
    coastline: true
    borders: false  # Removed borders as requested
    land: true
    ocean: true
    gridlines: true
  title:
    enabled: true
    text: "IMERG Daily Precipitation"
    date_format: "%d %B %Y"

output:
  images:
    enabled: true
    folder: "output/images"
    format: "png"
  gif:
    enabled: true
    folder: "output/animations"
    filename: "precipitation_2016_slow.gif"
    duration: 0.001
    loop: 0 